### ISSUE TITLE
Cannot access newtonsoft in new pull

### ISSUE THREAD

**Issue by holderl5** [pharindoko/serverlessDotNetStarter#25]
Greetings, 
I stumbled across this on Friday while looking for information on a new C# project I am about to embark upon.  I found that I am unable to compile when I try to access something from newtonsoft in Handler.cs.  See my output below:

`$ serverless create --template-url https://github.com/pharindoko/serverlessDotNetStarter --path dns3`
`Serverless: Generating boilerplate...`
`Serverless: Downloading and installing "serverlessDotNetStarter"...`
`(node:586272) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`
`(Use `node --trace-deprecation ...` to show where the warning was created)`
`Serverless: Successfully installed "serverlessDotNetStarter" `
`$ cd dns3/`
`$ diff Handler.cs ../serverlessDotnetstarter/Handler.cs`
`21c21,25`
`<             dict.Add("hello", "world");`
`---`
`>             var s = "{\"Tester\": \"Nope\"}";`
`>             var data = JObject.Parse(s);`
`> `
`>             dict.Add("hellooo", "world" + data["Tester"]);`
`>             //dict.Add("hellooo", "world" );`
`$ cp ../serverlessDotnetstarter/Handler.cs .`
`$ dotnet restore AwsDotnetCsharp.csproj`
`  Determining projects to restore...`
`  Restored /home/developer/dev/dns3/AwsDotnetCsharp.csproj (in 190 ms).`
`$ dotnet tool list -g`
`Package Id                      Version      Commands                   `
`------------------------------------------------------------------------`
`amazon.lambda.testtool-3.1      0.11.3       dotnet-lambda-test-tool-3.1`
`amazon.lambda.tools             5.1.1        dotnet-lambda`
`$ npm -v`
`6.14.11`
`$ node --version`
`v14.16.0`
`$ dotnet --version`
`5.0.202`
`$ sls --version`
`Framework Core: 2.33.1`
`Plugin: 4.5.3`
`SDK: 4.2.2`
`Components: 3.8.1`
`$ ./build.sh `
`E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)`
`E: Unable to lock directory /var/lib/apt/lists/`
`W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)`
`W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)`
`E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)`
`E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?`
`  Determining projects to restore...`
`  All projects are up-to-date for restore.`
`Amazon Lambda Tools for .NET Core applications (5.1.1)`
`Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet`
`Executing publish command`
`... invoking 'dotnet publish', working folder '/home/developer/dev/dns3/bin/Debug/netcoreapp3.1/publish'`
`... dotnet publish --output "/home/developer/dev/dns3/bin/Debug/netcoreapp3.1/publish" --configuration "Debug" --framework` `"netcoreapp3.1" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false `
`... publish: Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET`
`... publish: Copyright (C) Microsoft Corporation. All rights reserved.`
`... publish:   Determining projects to restore...`
`... publish:   Restored /home/developer/dev/dns3/AwsDotnetCsharp.csproj (in 214 ms).`
`... publish: /home/developer/dev/dns3/Handler.cs(22,24): error CS0103: The name 'JObject' does not exist in the current context`
`[/home/developer/dev/dns3/AwsDotnetCsharp.csproj]`
`Failed to create application package`

**Comment by pharindoko** [comment]
Hi @holderl5,

I have read your message and recreated a new project. This has built it without problems.
I then tested to use JObject Class from Netwtonsoft.

This code can be built without problems.

```
using System;
using System.Collections.Generic;
using System.Net;
using Amazon.Lambda.Core;
using Amazon.Lambda.APIGatewayEvents;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(
typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace AwsDotnetCsharp
{
    public class Handler
    {

        public APIGatewayProxyResponse HelloWorld(APIGatewayProxyRequest request, ILambdaContext context)
        {
            APIGatewayProxyResponse response;
            Dictionary<string, string> dict = new Dictionary<string, string>();
            dict.Add("hello", "world");

            var s = "{\"Tester\": \"Nope\"}";
            var data = JObject.Parse(s);

            response = CreateResponse(dict);
            return response;
        }

        public APIGatewayProxyResponse GetQuerystring(APIGatewayProxyRequest request, ILambdaContext context)
        {
            APIGatewayProxyResponse response;
            LogMessage(context, "Processing request started");
            if (request != null && request.QueryStringParameters.Count > 0)
            {
                try
                {
                    // var result = processor.CurrentTimeUTC();
                    response = CreateResponse(request.QueryStringParameters);
                    LogMessage(context, "First Parameter Value to read is: " + request.QueryStringParameters["foo"]);
                    LogMessage(context, "Processing request succeeded.");
                }
                catch (Exception ex)
                {
                    LogMessage(context, string.Format("Processing request failed - {0}", ex.Message));
                    response = CreateResponse(null);
                }
            }
            else
            {
                LogMessage(context, "Processing request failed - Please add queryStringParameter 'foo' to your request - see sample in readme");
                response = CreateResponse(null);
            }
            return response;
        }
        void LogMessage(ILambdaContext ctx, string msg)
        {
            ctx.Logger.LogLine(
                string.Format("{0}:{1} - {2}",
                    ctx.AwsRequestId,
                    ctx.FunctionName,
                    msg));
        }
        APIGatewayProxyResponse CreateResponse(IDictionary<string, string> result)
        {
            int statusCode = (result != null) ?
                (int)HttpStatusCode.OK :
                (int)HttpStatusCode.InternalServerError;

            string body = (result != null) ?
                JsonConvert.SerializeObject(result) : string.Empty;

            var response = new APIGatewayProxyResponse
            {
                StatusCode = statusCode,
                Body = body,
                Headers = new Dictionary<string, string>
                {
                    { "Content-Type", "application/json" },
                    { "Access-Control-Allow-Origin", "*" }
                }
            };

            return response;
        }

    }



}
```

If this does not fit, please share the handler.cs code or share a public repo to make it easy for me to fix this issue.

br,

@pharindoko

**Comment by holderl5** [comment]
Thanks for your reply.  
Adding:
`using Newtonsoft.Json.Linq;`
fixed the problem.  Apologies, I copied this snippet from an old project and didn't catch that using line at the top.  I probably didn't play with visual studio long enough to see the it warn me about my error.  Which leads to the next question I have:

I was able to use visual studio with the AWS toolkit extension and run in debug mode, however, I noticed that visual studio almost seems buggy in how it works depending on what command line build commands have been run.  Symptoms range from all of the all of the code being underlined in red, to the solution explorer showing a single line 
`**/resx` 
in place of all of the files in the directory.  Additionally, in another instance it would refuse to run the debug mode  a second time immediately after stopping and restarting debug mode.  Have you seen this behavior?  Do you have any insights?

Also, in your opinion, how does your template compare to building a layer zipfile with the desired libraries in the solution?

**Comment by holderl5** [comment]
![image](https://user-images.githubusercontent.com/25961276/115281464-a84a7c80-a10e-11eb-9263-1e33a1bef7b4.png)

I thought I would post this, as it happened just now.  The files are in the directory, I just opened it in visual studio and that is what I see.  I think running dotnet restore makes the files appear.

**Comment by pharindoko** [comment]
> Thanks for your reply.
> Adding:
> `using Newtonsoft.Json.Linq;`
> fixed the problem. Apologies, I copied this snippet from an old project and didn't catch that using line at the top. I probably didn't play with visual studio long enough to see the it warn me about my error. Which leads to the next question I have:
> 
> I was able to use visual studio with the AWS toolkit extension and run in debug mode, however, I noticed that visual studio almost seems buggy in how it works depending on what command line build commands have been run. Symptoms range from all of the all of the code being underlined in red, to the solution explorer showing a single line
> `**/resx`
> in place of all of the files in the directory. Additionally, in another instance it would refuse to run the debug mode a second time immediately after stopping and restarting debug mode. Have you seen this behavior? Do you have any insights?
> 
> Also, in your opinion, how does your template compare to building a layer zipfile with the desired libraries in the solution?

Sorry I have ran this solution always in visual studio code. I haven`t tried it in Visual studio itself. 
But the person I created if for used Visual Studio and there it worked. We have been able to even attach other nested libraries to the solution using the same project. 

Also, in your opinion, how does your template compare to building a layer zipfile with the desired libraries in the solution?
Youm mean AWS lambda layers ? I haven`t used layers but I´m not against it. It seems to be practical if you have more services that rely on a certain function / library. 
But I always attached the libraries directly to my lambda function as it is simple, testable and efficient to develop with.

**Comment by holderl5** [comment]
thanks for your assistance and your insight.
