### ISSUE TITLE
AWS LAMBDA FUNCTION HANDLER FOR RABBITMQ -- RABBITMQEVENT

### ISSUE THREAD

**Issue by aboah** [pharindoko/serverlessDotNetStarter#30]
I would be grateful if shown  the RabbitMQEvent class object( nugget package) that can be used to develop AWS Lambda Function.
Refer to AWS Lambda now supports Amazon MQ for RabbitMQ as an event source. Just as we have for Amazon.Lambda.S3Events
https://aws.amazon.com/about-aws/whats-new/2021/07/aws-lambda-now-supports-amazon-mq-for-rabbitmq-as-an-event-source/

**Comment by pharindoko** [comment]
Sorry but I have no time to create such a sample at the moment.
Maybe someone else can show an example how to integrate it into lambda....

This article should help ... https://www.serverless.com/framework/docs/providers/aws/events/rabbitmq
