### ISSUE TITLE
Amazon.Lambda.TestTool.WebTester31.dll does not exist

### ISSUE THREAD

**Issue by andcarey** [pharindoko/serverlessDotNetStarter#38]
I'm working on a Mac with VS Code.  In the readme, it mentions to use this in he launch.json if you're having problems.

  "program": /Users/{user}/.dotnet/tools/.store/amazon.lambda.testtool-3.1/{nuget-version}/amazon.lambda.testtool-3.1/{nuget-version}/tools/netcoreapp3.1/any/Amazon.Lambda.TestTool.WebTester31.dll",

The file Amazon.Lambda.TestTool.WebTester31.dll does not exist, so I used Amazon.Lambda.TestTool.BlazorTester.dll instead and it works.

I found this clue here: https://stackoverflow.com/questions/65039118/unable-to-debug-lambda-locally-in-rider

**Comment by pharindoko** [comment]
@andcarey thanks for the hint
I updated it now to .net 6
Have to test it on my mac again - can you try it out again  ?

br
