### ISSUE TITLE
Incorrect program setting in docs

### ISSUE THREAD

**Issue by futurify-ydang** [pharindoko/serverlessDotNetStarter#9]
Please update the docs to the correct dll: **Amazon.Lambda.TestTool.WebTester31.dll**
![image](https://user-images.githubusercontent.com/44663784/82977987-ab77de00-a00d-11ea-96ab-96a79a0f120b.png)

Follow to above image I've added the path of **Amazon.Lambda.TestTool.dll** to **launch.json** but it's incorrect. The **dll** should be **Amazon.Lambda.TestTool.WebTester31.dll**

**Comment by pharindoko** [comment]
Thanks a lot for the hint. I fixed it.
